### ISSUE TITLE
Vd- view is down ?

### ISSUE THREAD

**Issue by brianmartin2001** [simonlaszcz/vd-view#7]
Simon , any issue with vd view? It has been down for a long while.

Can you advise if there's an issue.

I sent you an email, can you reply to me there 

Many thanks 
Brian

**Comment by simonlaszcz** [comment]
Thanks for letting me know. I'll take a look. Probably an Azure thing

**Comment by simonlaszcz** [comment]
Now back online

**Comment by brianmartin2001** [comment]
Wonderful , cheers Simon
    On Thursday 30 May 2024 at 13:04:25 BST, Simon Laszcz ***@***.***> wrote:  
 
 


Now back online
